### ISSUE TITLE
Consider Factory pattern for UpdateRepository

### ISSUE THREAD

**Issue by janhoy** [decebals/pf4j-update#10]
Today there is a fixed concrete `UpdateRepository` class which makes a number of assumptions about a repo. The UpdateManager assumes all UpdateRepos are of that exact class.

If we used the Factory pattern here, with method `public UpdateRepository create(String id, String location)`, then we the default factory would create today's `DefaultUpdateRepository`, but users could also provide their own factories to support more complex setups, and `UpdateManager` would work on interfaces instead.

Example: For Apache Solr I'm planning to write an `ApacheDownloadMirrorUpdateRepository` which will allow download from the official release repos, resolve closest mirror (or fallback to central archive) that has the correct version, and download & validate `{file}.md5`. I'm also envisioning a central canonical repo which only acts as pointers to 3rd party plugins. This central repo might be something like `GitHubUpdateRepository` where location is `https://github.com/{user}/{repo}/` and looking for `plugins.json` in `https://raw.githubusercontent.com/{user}/{repo}/master/plugins.json`.

What do you think?

**Comment by decebals** [comment]
Make sense what you say.
I see that `UpdateManager` uses only `getPlugins()` method from the `UpdateRepository` class so, we can rename actual `UpdateRepository` class to `DefaultUpdateRepository` and extract an interface `UpdateRepository` that contains the `getPlugins()` method (and other possible methods).
I don't feel that we need a Factory method (`create`). The `UpdateManager` works with a list of `UpdateRepository`(s) and it's enough this info. The creation/instantiation of repositories list is made outside of UpdateManager. Eventually we can add more helper methods in UpdateManager (for example  `addRepository(UpdateRepository repository)').

**Comment by janhoy** [comment]
Good plan, will try to implement one of my planned repositories without use of factory and submit a PR for a minimum solution.
