### ISSUE TITLE
InstallPlugin does not unzip after download

### ISSUE THREAD

**Issue by janhoy** [decebals/pf4j-update#4]
Testing the UpdateManager, but run in to a problem with `installPlugin(url)`.
See stack trace here: https://gist.github.com/fde87ba46316ba24ff886067feea48bb in particular:

    100206 ERROR (main) [    ] r.f.p.AbstractPluginManager plugins/extraction-6.5.0.zip/classes/META-INF/MANIFEST.MF: Not a directory

Is the intention that the installer will download and then unzip the plugin into the plugins folder,
or should the PluginManager load the plugin from within the ZIP file?

**Comment by decebals** [comment]
`UpdateManager` only fetch/download the new plugin or plugin version (zip file) to plugins folder. `PF4J` 1.2.0 comes with a refactoring that probably introduce a bug in combination with `UpdateManager`.
I will check on a demo application. If you have a such quick start application that reproduce the problem in an easy mode, please let me know.
Thanks for reporting this issue.

**Comment by janhoy** [comment]
My code is simply calling

    updateManager.installPlugin(url_to_zip);

The problem is that `installPlugin(String url)` downloads the ZIP, then  passes the Path of the ZIP file to `pluginManager.loadPlugin(Path)`, which expects a folder.

I have worked around it locally by overriding installPlugin and explicitly unzipping before calling loadPlugin. But I'm sure there is a more generic way?

**Comment by decebals** [comment]
It's a bug introduced by last PF4J. I will come with a patch.

**Comment by janhoy** [comment]
This also affects `updateManager.updatePlugin()`.

I think it is not correct to call `loadPlugin` and `startPlugin` from pf4j-update. The use I envision for Solr is actually running plugin install, uninstall, delete etc on a "cold", not running server using a CLI tool, that won't need that the plugins start up.

Can PluginManager poll the file system instead?

**Comment by decebals** [comment]
I think that API of `UpdateManager` is good and the methods `installPlugin` and `updatePlugin` are useful.
I understand for what you wrote in your last comment that you don't want to load and start the plugin on `installPlugin` and `updatePlugin`, am I right (https://github.com/decebals/pf4j-update/blob/master/src/main/java/ro/fortsoft/pf4j/update/UpdateManager.java#L173)?

> Can PluginManager poll the file system instead?

Can you add more details, please?

**Comment by janhoy** [comment]
I guess it is not a huge problem if the plugin is loaded and started in the CLI tool, as it will simply die again once the command completes and never be used. The only problem I could imagine is that if a plugin that gets started has some assumptions about running in the full system and then perhaps fails if it cannot find certain things?

> Can you add more details, please?
If pf4j-update will not start the plugin, then I guess PluginManager could have that responsibility, e.g. by polling for new ZIP files or folders in the plugins folder. It is dangerous too, since pf4j-update may be in the middle of writing a zip file. That could be solved by PluginManager polling file size of a new file until it does not change.

What would happen if my server runs with plugins loaded, and then my CLI JVM process comes along updating a plugin by deleting the old one and installing the new one. The PluginManager in the server will probably get confused and will not know that the plugin got upgraded under its feet. Could the two processes acquire write permission to plugins folder through a `write.lock` file? Once the server finds a write.lock that it dit not put there itself, it would close all open file handles. And once it finds e.g. `write.done` it could trigger a `loadPlugins()`? Or we'll simply need to handle it all on application level outside of pf4j.

**Comment by decebals** [comment]
Probably the simple solution is to add a parameter `boolean start/starting` in the signature of methods `UpdateManager.installPlugin` and `UpdateManager.updatePlugin,` and to load and start the plugin according this flag:
```
if (start) {
    String pluginId = pluginManager.loadPlugin(pluginArchiveFile.toPath());
    PluginState state = pluginManager.startPlugin(pluginId);
}
``` 
Eventually we can keep the short methods (without `start` flag) and to call the long methods with a default for `start` parameter (true or false - I am not sure):
```
public boolean installPlugin(String url) {
    return installPlugin(url, true/false);
}
```

In this mode you can have a full control on install, update, load and start plugin.

What you think?

**Comment by janhoy** [comment]
Closing this for now. Will perhaps add a new issue for handling detached client and server later.
