### ISSUE TITLE
PluginRelease.requires is different from PluginDescriptor.requires

### ISSUE THREAD

**Issue by janhoy** [decebals/pf4j-update#7]
The `requires` string in releases section of `plugins.json` takes a single `Version` while the `Plugin-Requires` in the MANIFEST takes an expression. Since these two are meant to express the same constraint, they should both have the same syntax so one won't need to compute two different require strings.

Should not be a problem to switch to `Expression` since we're still on a `0.x.x` version for pl4j-update.

**Comment by decebals** [comment]
My solution is to use `String` for `requires` attribute in both classes (`PluginDescriptor` and `PluginRelease`), to have a method `getRequires()` that returns a String and a method `getRequiresExpression()` (sure in PluginDescriptor - I am not sure that is necessary in PluginRelease) that returns an Expression instance.
The `requires` attribute from `PluginDescriptor` is not used for now (from my acknowledges) so we can make the modifications without to worry about the backward incompatibilities.
